apiVersion: v1
kind: Service

metadata:
  name: next-service

spec:
  type: NodePort
  selector:
    app: next-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
